<script>
    //===========================================Что такое Promise??=================================

    //Promise - это объект. Синтаксис создания:

    let promise = new Promise(function (resolve, reject) {
        //тело функции исполнителя, которая возвращает значение value

        let a = 2;

        let b = a + a ** 2;
        let sum = a + b;

        //функции колбэки resolve и reject

        //resolve выполняется в случае успешного выполнения фунукции исполнителя и принимает значение функции исполнителя
        resolve(sum);

        //reject выполняется в случае возникновения ошибки функции исполнителя и принимает ошибку
        reject(error);

    });

    //У объекта promise есть внутренние свойства state и result

    // Поговорим про свойствао state

    // оно показывает состояние объекта. До выполнения функции исполнителя состояние объекта promise
    // будет следующим "pending (ожидание)", затем после выполнения функции исполнителя объект примет одно из двух состояний "fulfilled (выполнено успешно)" 
    //или "rejected (выполнено с ошибкой)", "fulfilled" будет при успешном выполнении кода функции исполнителя, а rejected при возникновении ошибок

    // Свойство result

    // оно принимает значение value, то что мы передает в resolve (value) при успешном выполнении
    // и оно принимает error при возниковении reject(error)

    //Посмотрим наш объект promise

    // console.log(promise); //статус будет fulfilled(выполнено успешно) и result = 8


    //==========================THEN, CATCH, FiNALLY=========================================================

    //Объект promise служит связующим звеном между функцией исполнителем и функциями-потребителями.
    //Функции-потребители записываются с помощью методов .then, .catch, .finally

    // метод .then(f1, f2) принимает 2 функции колбэка, 
    // первая функция f1 принимает result и срабатывает в случае, если статус объекта promise = fulfilled(успешно выполено)
    // вторая функция f2 принимает error и срабатывает при статусе объекта promise = rejected(выполнено с ошибками)

    //рассмотрим пример с нашим объектом promise:

    // promise.then(
    //     (sum) => { console.log('result: ', sum) }, // сработает только этот колбэк, так как статут fulfilled  -  result: 8
    //     (error) => { console.log('Error: ', error) }
    // ); // result: 8

    // допустим ошибку и закомментируем значение переменной a (см. код выше)
    // тогда сработает 2-я функция колбэк и выдаст в консоли след. сообщение: "ReferenceError: a is not defined"

    // ВАЖНАЯ ОСОБЕННОСТЬ МЕТОД .THEN ВОЗВРАЩАЕТ ОБЪЕКТ PROMISE. ПОЭТОМУ МЕТОД THEN МОЖНО ИСПОЛЬЗОВАТЬ ПО ЦЕПОЧКЕ


    //===========CATCH(f) - метод принимает функцию колбэк f, данный метод позволяет нам обработать только ошибку

    // promise.catch(error => { console.log('Error: ', error) });

    // МЕТОД CATCH НЕ ВОЗВРАЩАЕТ ОБЪЕКТ PROMISE ОН ОСТАНАВЛИВАЕТ ЦЕПЕЧКУ


    //===========FINALLY(f) - метод принимает функцию колбэк f, данный метод срабатывае и при ошибке и при успешном выполнении

    // promise.finally(() => { console.log('Method Finally') });

    //МЕТОД FINALLY НЕ ОСТАНАВЛИВАЕТ ЦЕПОЧКУ И ПРОПУСКАЕТ PROMISE ДАЛЬШЕ

    // promise.then((sum) => { console.log('result: ', sum) });


    //===================ПРИМЕР==================================

    //     function loadScript(src) {
    //     return new Promise(function(resolve, reject) {
    //     let script = document.createElement('script');
    //     script.src = src;

    //     script.onload = () => resolve(script);
    //     script.onerror = () => reject(new Error(`Ошибка загрузки скрипта ${src}`));

    //     document.head.append(script);
    //   });
    //}

    // ВЫЗОВ

    // let promise = loadScript("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js");

    // promise.then(
    //     script => alert(`${script.src} загружен!`),
    //     error => alert(`Ошибка: ${error.message}`)
    // );

    // promise.then(script => alert('Ещё один обработчик...'));

</script>